insert into DISCIPLINA (disciplina_id, clave, nombre, descripcion, icono) values (1, 'fjA6beLJ', 'pede', 'fusce posuere felis sed lacus morbi sem', empty_blob());
insert into DISCIPLINA (disciplina_id, clave, nombre, descripcion, icono) values (2, 'J8AFZfQ2', 'risus', 'maecenas ut massa quis', empty_blob());
insert into DISCIPLINA (disciplina_id, clave, nombre, descripcion, icono) values (3, 'TLgjpUOD', 'sit', 'sed accumsan felis ut at dolor quis odio consequat varius', empty_blob());
insert into DISCIPLINA (disciplina_id, clave, nombre, descripcion, icono) values (4, 'K73xVu7H', 'mauris', 'cubilia curae donec pharetra magna vestibulum aliquet ultrices', empty_blob());
insert into DISCIPLINA (disciplina_id, clave, nombre, descripcion, icono) values (5, 'zY5tepmg', 'ac', 'dui luctus rutrum nulla tellus in sagittis dui', empty_blob());
insert into DISCIPLINA (disciplina_id, clave, nombre, descripcion, icono) values (6, 'WCwrlX2O', 'rhoncus', 'imperdiet et commodo vulputate', empty_blob());
insert into DISCIPLINA (disciplina_id, clave, nombre, descripcion, icono) values (7, 'vhSKav0N', 'aliquam', 'sapien dignissim vestibulum vestibulum', empty_blob());
insert into DISCIPLINA (disciplina_id, clave, nombre, descripcion, icono) values (8, 'YfRVBdoW', 'nec', 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien', empty_blob());
insert into DISCIPLINA (disciplina_id, clave, nombre, descripcion, icono) values (9, 'SVc6zbma', 'duis', 'nonummy', empty_blob());
insert into DISCIPLINA (disciplina_id, clave, nombre, descripcion, icono) values (10, 'EJEuM4OA', 'ullamcorper', 'at nulla suspendisse potenti cras in purus eu magna vulputate', empty_blob());