--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      DATA MODEL
-- Author :       carlos_amador1@comunidad.unam.mx
--
-- Date Created : Saturday, May 14, 2022 20:44:53
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    CLIENTE_ID          NUMBER(10, 0)     NOT NULL,
    NOMBRE              VARCHAR2(40)      NOT NULL,
    AP_PAT              VARCHAR2(40)      NOT NULL,
    AP_MAT              VARCHAR2(40),
    EMAIL               VARCHAR2(40)      NOT NULL,
    USERNAME            VARCHAR2(40)      NOT NULL,
    PASSWORD            VARCHAR2(40)      NOT NULL,
    DIRECCION           VARCHAR2(4000)    NOT NULL,
    FECHA_NACIMIENTO    DATE              NOT NULL,
    CURP                VARCHAR2(18)      NOT NULL,
    FOTO                BLOB              NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: SESION 
--

CREATE TABLE SESION(
    SESION_ID       NUMBER(10, 0)    NOT NULL,
    NUM_SESION      NUMBER(10, 0)    NOT NULL,
    FECHA_INICIO    DATE             NOT NULL,
    DURACION        DATE,
    FECHA_FIN       DATE             NOT NULL,
    TIPO            VARCHAR2(10)     NOT NULL,
    EMP_INST_ID     NUMBER(10, 0)    NOT NULL,
    CLIENTE_ID      NUMBER(10, 0)    NOT NULL,
    SALA_ID         NUMBER(10, 0),
    CONSTRAINT PK12 PRIMARY KEY (SESION_ID), 
    CONSTRAINT RefCLIENTE2 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: BITACORA 
--

CREATE TABLE BITACORA(
    BITACORA_ID    NUMBER(10, 0)    NOT NULL,
    FECHA          DATE             NOT NULL,
    CALORIAS       NUMBER(10, 4)    NOT NULL,
    SESION_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK13 PRIMARY KEY (BITACORA_ID), 
    CONSTRAINT RefSESION3 FOREIGN KEY (SESION_ID)
    REFERENCES SESION(SESION_ID)
)
;



-- 
-- TABLE: CREDENCIAL 
--

CREATE TABLE CREDENCIAL(
    CLIENTE_ID    NUMBER(10, 0)    NOT NULL,
    FOLIO         VARCHAR2(8)      NOT NULL,
    VIGENCIA      DATE             NOT NULL,
    COD_BARRAS    NUMBER(13, 0)    NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (CLIENTE_ID), 
    CONSTRAINT RefCLIENTE1 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: REPORTE 
--

CREATE TABLE REPORTE(
    REPORTE_ID    NUMBER(10, 0)    NOT NULL,
    PESO          NUMBER(10, 4)    NOT NULL,
    IMC           NUMBER(10, 4),
    ESTATURA      NUMBER(10, 4),
    FECHA         DATE             NOT NULL,
    CLIENTE_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK14 PRIMARY KEY (REPORTE_ID), 
    CONSTRAINT RefCLIENTE5 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: SENSOR 
--

CREATE TABLE SENSOR(
    SENSOR_ID       NUMBER(10, 0)    NOT NULL,
    NUM_SERIE       NUMBER(20, 0)    NOT NULL,
    FECHA_COMPRA    DATE             NOT NULL,
    MARCA           VARCHAR2(40)     NOT NULL,
    CLIENTE_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK11 PRIMARY KEY (SENSOR_ID), 
    CONSTRAINT RefCLIENTE4 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
)
;



-- 
-- TABLE: SESION_DISPOSITIVO 
--

CREATE TABLE SESION_DISPOSITIVO(
    SESION_DISPOSITIVO_ID    NUMBER(10, 0)    NOT NULL,
    SESION_ID                NUMBER(10, 0)    NOT NULL,
    DISPOSITIVO_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK27 PRIMARY KEY (SESION_DISPOSITIVO_ID), 
    CONSTRAINT RefSESION6 FOREIGN KEY (SESION_ID)
    REFERENCES SESION(SESION_ID)
)
;



